### PR TITLE
Fix coverage on child_process runner

### LINKED ISSUE #90: Can't collect coverage when running in child_process
Similar issue in [jest](https://github.com/jestjs/jest/issues/5274) [vitest](https://github.com/vitest-dev/vitest/discussions/3851)

### PR DESCRIPTION
**Pull request by fisker**
@liuxingbaoyu Come up a solution on our side instead of patching tinypool, based on your patch https://github.com/nicolo-ribaudo/jest-light-runner/issues/90#issuecomment-2812473389

Fixes #90

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -53,24 +53,44 @@ const createRunner = ({ runtime = "worker_threads" } = {}) =>
...
+            }
+
+            for (const worker of this._pool.threads) {
+              if (!workers.has(worker)) {
+                workers.add(worker);
+                // Use `process.disconnect()` instead of `process.kill`, so we can collect coverage
+                // See https://github.com/nicolo-ribaudo/jest-light-runner/issues/90#issuecomment-2812473389
+                worker.process.kill = worker.process.disconnect;
+              }
+            }
```
Comment (liuxingbaoyu) [inline src/index.js:86]: Can we move them before `await pool.destroy()` and remove `workers`?

Comment (fisker) [reply src/index.js:86]: Current code seems not working on CI, but it did work on my machine.

Comment (liuxingbaoyu) [reply src/index.js:86]: Are you running Windows? I suspect it may be system related.

Comment (fisker) [reply src/index.js:86]: Yes, I'm on Windows.

Comment (fisker) [reply src/index.js:86]: Still nothing on Windows https://github.com/nicolo-ribaudo/jest-light-runner/actions/runs/14520035657/job/40738481319?pr=92#step:7:1365

Comment (fisker) [reply src/index.js]: Tested on Linux on gitpod.io, works too.

File: .github/workflows/e2e-tests.yml [hunk 2]
```diff
@@ -63,6 +63,49 @@ jobs:
...
+        working-directory: prettier
+
+      - name: Update jest-light-runner
+        run: |
+          yarn up jest-light-runner@file:../jest-light-runner
+        working-directory: prettier
+
+      - name: Run tests
+        env:
+          NODE_ENV: production
```
Comment (liuxingbaoyu) [inline .github/workflows/e2e-tests.yml:103]: Its cause.🤦‍♂️

Comment (fisker) [reply .github/workflows/e2e-tests.yml:103]: ... Thanks!

Comment (fisker) [reply .github/workflows/e2e-tests.yml:100]: No wonder `--runInBand` doesn't collect anything either, I was so stupid.

Comment (liuxingbaoyu) [reply .github/workflows/e2e-tests.yml]: It doesn't matter.:)

File: src/index.js (hunk 1 above)
Comment (fisker) [reply src/index.js]: > Can we move `worker.process.kill = worker.process.disconnect` before `await pool.destroy()` and remove `workers`?

Looks like move the end works, but I'm not sure if it will be called internally before we call `pool.destroy()`.

Comment (liuxingbaoyu) [reply src/index.js]: As of now, no, it just calls `process.unref().`

Comment (fisker) [reply src/index.js]: Look like the subprocess will die, I tested `isolateWorkers: true`

https://github.com/fisker/jest-light-runner/actions/runs/14521140796/job/40742114663?pr=92#step:7:1376

Comment (fisker) [reply src/index.js]: But you are right, collecting workers won't help.

Can you help me take another look? I'll merge if the current code looks good to you.

Thanks a lot for the help!

File: src/index.js [hunk 3]
```diff
@@ -62,15 +63,29 @@ const createRunner = ({ runtime = "worker_threads" } = {}) =>
...
+            // Use `process.disconnect()` instead of `process.kill()`, so we can collect coverage
+            // See https://github.com/nicolo-ribaudo/jest-light-runner/issues/90#issuecomment-2812473389
+            // Only override the first call https://github.com/tinylibs/tinypool/blob/dbf6d74282dd6031df8fc5c7706caef66b54070b/src/runtime/process-worker.ts#L61
+            const originalKill = process.kill;
+            process.kill = signal => {
+              if (!signal) {
+                process.disconnect();
+                process.kill = originalKill;
+              }
+              return originalKill.call(process, signal);
```
Comment (liuxingbaoyu) [inline src/index.js:83]: Currently we call `originalKill.call(process, signal)` after `process.disconnect()`, is this expected?

Comment (fisker) [reply src/index.js:83]: No, mistake.

I mean to only call `disconnect()` as your patch did to replace https://github.com/tinylibs/tinypool/blob/dbf6d74282dd6031df8fc5c7706caef66b54070b/src/runtime/process-worker.ts#L61

But it seems call `.disconnect()` before `.kill()` also works, let's keep it?

Comment (fisker) [reply src/index.js:83]: No, I should return...

**Review by liuxingbaoyu — APPROVED** [review]
This PR looks good to me.
However, the coverage is still lower than `--runInBand`, which is strange.

**Comment by fisker** [comment]
> However, the coverage is still lower than --runInBand, which is strange.

Better than nothing 😄
