### PR TITLE
Reload imported modules in `--watch` mode

### LINKED ISSUE #37: "Your test suite must contain at least one test" with --runInBand and --watch
Hi, I'm getting the following error on subsequent test runs, (as in, the first run works fine, but any runs after making any changes give this error) when running with --runInBand and --watch:

```bash   
    FAIL  src/__tests__/bar.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:172:18)
          at async Promise.all (index 0)
```

I made a mini reproduction repo here with instructions in the readme:

https://github.com/cjroebuck/jest-light-runner-runInBand-watch-bug-repro

I have tracked down the issue to this line https://github.com/nicolo-ribaudo/jest-light-runner/blob/main/src/worker-runner.js#L99

It seems that when run with --runInBand, the dynamic import when using `InBandPiscina` class is cached on subsequent test runs, and jest-circus fails to pick up the tests.

A hacky fix I made for this is to stick a random hash on the end of the import file path as a query parameter to 'bust' the import module cache, i.e.:

`await import(pathToFileURL(testFile));`

becomes

`await import(pathToFileURL(testFile)+"?"+Date.now());`

This works, but feels quite hacky and would probably lead to memory leaks if used in watch mode for many hours.

### PR DESCRIPTION
**Pull request by cjroebuck**
temporarily fixes #37

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks! Sorry for not reviewing this earlier, it looks like a good workaround.

File: src/worker-runner.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ export default async function run({
 
 async function loadTests(testFile) {
   circus.resetState();
-  await import(pathToFileURL(testFile));
+  await import(pathToFileURL(testFile)+"?"+Date.now());
```
Comment (nicolo-ribaudo) [inline src/worker-runner.js:99]:
```suggestion
  await import(pathToFileURL(testFile) + "?" + Date.now());
```
